package com.toms.android.adivinaadivinador.database

public var listOfAnimals: MutableList<String> = mutableListOf(
    "vaca",
    "perro",
    "abeja",
    "águila",
    "araña",
    "avispa",
    "ballena",
    "bisonte",
    "búfalo",
    "burro",
    "caballo",
    "camello",
    "canario",
    "cangrejo",
    "canguro",
    "caracol",
    "cebra",
    "cerdo",
    "chimpancé",
    "ciervo",
    "cisne",
    "cocodrilo",
    "conejo",
    "elefante",
    "escarabajo",
    "escorpión",
    "foca",
    "gallina",
    "gallo",
    "gato",
    "golondrina",
    "hipopótamo",
    "hormiga",
    "jabalí",
    "jirafa",
    "koala",
    "león",
    "loro",
    "mosca",
    "mosquito",
    "oso",
    "oveja",
    "orangutan",
    "pavo real",
    "perdiz",
    "perro",
    "pingüino",
    "pollo",
    "saltamontes",
    "serpiente",
    "tigre",
    "topo",
    "toro",
    "tortuga",
    "vaca",
    "zorro"
)
public var listOfAnimalsForKids: MutableList<String> = mutableListOf(
    "vaca",
    "perro",
    "ballena",
    "burro",
    "caballo",
    "camello",
    "pajaro",
    "cangrejo",
    "canguro",
    "caracol",
    "cerdo",
    "mono",
    "pato",
    "cocodrilo",
    "elefante",
    "foca",
    "gallina",
    "gato",
    "hipopótamo",
    "hormiga",
    "jirafa",
    "león",
    "loro",
    "mosquito",
    "oso",
    "oveja",
    "perro",
    "pingüino",
    "serpiente",
    "tigre",
    "tortuga",
    "conejo",
    "mariposa",
    "koala",
    "pez"
)
public var listOfCities: MutableList<String> = mutableListOf(
    "Tokio",
    "Nueva York",
    "Los Ángeles",
    "Seúl",
    "Londres",
    "París",
    "Osaka",
    "Shanghái",
    "Chicago",
    "Moscú",
    "Pekín",
    "Colonia",
    "Houston",
    "Washington D. C.",
    "São Paulo",
    "Hong Kong",
    "Dallas",
    "Ciudad de México",
    "Cantón",
    "Tianjin",
    "Singapur",
    "Nagoya",
    "Shenzhen",
    "Boston",
    "Estambul",
    "Filadelfia",
    "Suzhou",
    "San Francisco",
    "Taipéi",
    "Yakarta",
    "Ámsterdam",
    "Buenos Aires",
    "Chongqing",
    "Milán",
    "Bangkok",
    "Busan",
    "Atlanta",
    "Delhi",
    "Toronto",
    "Seattle",
    "Miami",
    "Madrid",
    "Bruselas",
    "Chengdu",
    "Wuhan",
    "Frankfurt",
    "Sídney",
    "Múnich",
    "Hangzhou",
    "Wuxi",
    "Minneapolis",
    "Qingdao",
    "Detroit",
    "Phoenix",
    "Nanjing",
    "San Diego",
    "Dalian",
    "Fukuoka",
    "Shenyang",
    "Changsha",
    "Foshan",
    "Viena",
    "Manila",
    "Ningbo",
    "Melbourne",
    "Abu Dhabi",
    "Río de Janeiro",
    "Lima",
    "Baltimore",
    "Kuala Lumpur",
    "Santiago de Chile",
    "Barcelona",
    "Denver",
    "Kuwait",
    "Riad",
    "Roma",
    "Tangshan",
    "Hamburgo",
    "Jeddah",
    "San Jose",
    "Bogotá",
    "Portland",
    "Stuttgart",
    "Berlín",
    "Zhengzhou",
    "Montreal",
    "Riverside",
    "Tel Aviv",
    "Mumbai",
    "Yantai",
    "Estocolmo",
    "Brasilia",
    "Dongguan",
    "Varsovia",
    "San Luis",
    "Pittsburgh",
    "Karlsruhe",
    "Jinan",
    "Perth",
    "Shijiazhuang",
    "Tampa",
    "Atenas",
    "Nantong",
    "Harbin",
    "Sacramento",
    "Copenhague",
    "Charlotte",
    "Changchun",
    "Xi'an",
    "Monterrey",
    "Katowice",
    "Birmingham",
    "Hefei",
    "San Petersburgo",
    "Fuzhou",
    "Orlando",
    "Cleveland",
    "Taichung",
    "Kaohsiung",
    "Indianapolis",
    "Xuzhou",
    "Cincinnati",
    "Changzhou",
    "Vancouver",
    "Zúrich",
    "Columbus",
    "Austin",
    "Kansas City",
    "Ankara",
    "San Antonio",
    "El Cairo",
    "Wenzhou",
    "Hartford",
    "Zibo",
    "Aachen",
    "Lille",
    "Daqing",
    "Budapest",
    "Calgary",
    "Lyon",
    "Brisbane",
    "Lisboa",
    "Nanchang",
    "Nashville",
    "Baotou",
    "Las Vegas",
    "Mánchester",
    "Virginia Beach",
    "Eindhoven",
    "Dublín",
    "Praga",
    "Kunming",
    "Taoyuan",
    "Milwaukee",
    "Nápoles",
    "Belo Horizonte",
    "Dongying",
    "Edmonton",
    "Johannesburgo",
    "Dubái",
    "Guadalajara",
    "Sapporo",
    "Bursa",
    "Esmirna",
    "Turín",
    "Providence",
    "Helsinki",
    "Tainan",
    "Xiamen",
    "Sendai",
    "Hiroshima",
    "Leeds",
    "Nürnberg",
    "Oslo",
    "Nueva Orleans",
    "Salt Lake City",
    "Búfalo",
    "Bucarest",
    "Richmond",
    "Ciudad Ho Chi Minh",
    "Nanning",
    "Hohhot",
    "Oklahoma City",
    "Bridgeport",
    "Zhongshan",
    "Rochester",
    "Anshan",
    "Liverpool",
    "Memphis",
    "Raleigh",
    "Jacksonville",
    "Taiyuan",
    "Luxemburgo",
    "Louisville",
    "Porto Alegre",
    "Calcuta",
    "Marseille",
    "Hannover",
    "Urumchi",
    "Campinas",
    "Ciudad del Cabo",
    "Honolulu",
    "Chennai",
    "Shizuoka",
    "Albany",
    "Ottawa",
    "Curitiba",
    "Venecia",
    "Okayama",
    "Glasgow",
    "Basel",
    "East Rand",
    "Daegu",
    "Birmingham",
    "Macau",
    "Baton Rouge",
    "New Haven",
    "Almaty",
    "Valencia",
    "Florencia",
    "Hamamatsu",
    "Caracas",
    "Portsmouth",
    "Grand Rapids",
    "Omaha",
    "Nottingham",
    "Bielefeld",
    "Niigata",
    "Pretoria",
    "Auckland",
    "Durban",
    "Tulsa",
    "Bremen",
    "Bakersfield",
    "Bristol",
    "Adelaide",
    "Toulouse",
    "Oxnard",
    "Nice",
    "Braunschweig",
    "Fresno",
    "Bangalore",
    "Worcester",
    "Newcastle",
    "Linz",
    "Arnhem",
    "Ginebra",
    "Sofia",
    "Medellín",
    "Porto",
    "San Juan",
    "Kumamoto",
    "Madison",
    "Saarbrucken",
    "Zhuhai",
    "Tucson",
    "Greensboro",
    "Little Rock",
    "Syracuse",
    "Recife",
    "Haifa",
    "Bordeaux",
    "Hyderabad",
    "Gotemburgo",
    "Albuquerque",
    "Sheffield",
    "Daejeon",
    "Leipzig",
    "Des Moines",
    "Shantou",
    "Bilbao",
    "Salvador",
    "Hsinchu",
    "Knoxville",
    "Puebla",
    "George Town",
    "Casablanca",
    "Dayton",
    "Allentown",
    "Strasbourg",
    "Columbia",
    "Durham",
    "Gwangju",
    "Bolonia",
    "Cardiff",
    "Sevilla",
    "Vitória",
    "Greenville",
    "Fortaleza",
    "Harrisburg",
    "Kagoshima",
    "Quebec",
    "Cracovia",
    "Akron",
    "Springfield",
    "El Paso",
    "Edimburgo",
    "Winnipeg",
    "Alejandría",
    "Nantes"
)

public var listOfStuffs: MutableList<String> = mutableListOf(
    "tijera",
    "peine",
    "cepillo",
    "escoba",
    "silla",
    "mesa",
    "coche",
    "sirena",
    "cesto",
    "sillón",
    "televisor",
    "radio",
    "robot",
    "celular",
    "soldado",
    "casa",
    "caja"
)