package com.toms.android.adivinaadivinador.database

public var listOfAnimals: List<String> = listOf(
    "vaca",
    "perro",
    "abeja",
    "águila",
    "araña",
    "avispa",
    "ballena",
    "bisonte",
    "búfalo",
    "burro",
    "caballo",
    "camello",
    "canario",
    "cangrejo",
    "canguro",
    "caracol",
    "cebra",
    "cerdo",
    "chimpancé",
    "ciervo",
    "cisne",
    "cocodrilo",
    "conejo",
    "elefante",
    "escarabajo",
    "escorpión",
    "foca",
    "gallina",
    "gallo",
    "gato",
    "golondrina",
    "hipopótamo",
    "hormiga",
    "jabalí",
    "jirafa",
    "koala",
    "león",
    "loro",
    "mosca",
    "mosquito",
    "oso",
    "oveja",
    "orangutan",
    "pavo real",
    "perdiz",
    "perro",
    "pingüino",
    "pollo",
    "saltamontes",
    "serpiente",
    "tigre",
    "topo",
    "toro",
    "tortuga",
    "vaca",
    "zorro"
)
public var listOfAnimalsForKids: List<String> = listOf(
    "vaca",
    "perro",
    "ballena",
    "burro",
    "caballo",
    "camello",
    "pajaro",
    "cangrejo",
    "canguro",
    "caracol",
    "cerdo",
    "mono",
    "pato",
    "cocodrilo",
    "elefante",
    "foca",
    "gallina",
    "gato",
    "hipopótamo",
    "hormiga",
    "jirafa",
    "león",
    "loro",
    "mosquito",
    "oso",
    "oveja",
    "perro",
    "pingüino",
    "serpiente",
    "tigre",
    "tortuga",
    "conejo",
    "mariposa",
    "koala",
    "pez"
)
public var listOfCities:  List<String> = listOf(
    "Tokio",
    "Nueva York",
    "Los Ángeles",
    "Seúl",
    "Londres",
    "París",
    "Osaka",
    "Shanghái",
    "Chicago",
    "Moscú",
    "Pekín",
    "Houston",
    "Washington D.C.",
    "São Paulo",
    "Hong Kong",
    "Dallas",
    "Ciudad de México",
    "Singapur",
    "Boston",
    "Estambul",
    "Filadelfia",
    "San Francisco",
    "Ámsterdam",
    "Buenos Aires",
    "Milán",
    "Bangkok",
    "Busan",
    "Atlanta",
    "Delhi",
    "Toronto",
    "Seattle",
    "Miami",
    "Madrid",
    "Bruselas",
    "Wuhan",
    "Frankfurt",
    "Sídney",
    "Múnich",
    "Minneapolis",
    "Detroit",
    "Phoenix",
    "San Diego",
    "Viena",
    "Manila",
    "Río de Janeiro",
    "Lima",
    "Kuala Lumpur",
    "Santiago de Chile",
    "Barcelona",
    "Denver",
    "Kuwait",
    "Roma",
    "Hamburgo",
    "Bogotá",
    "Berlín",
    "Montreal",
    "Tel Aviv",
    "Mumbai",
    "Estocolmo",
    "Brasilia",
    "Varsovia",
    "San Luis",
    "Pittsburgh",
    "Atenas",
    "Copenhague",
    "Monterrey",
    "San Petersburgo",
    "Orlando",
    "Cleveland",
    "Vancouver",
    "Zúrich",
    "Austin",
    "El Cairo",
    "Budapest",
    "Lyon",
    "Lisboa",
    "Las Vegas",
    "Mánchester",
    "Dublín",
    "Praga",
    "Nápoles",
    "Dubái",
    "Guadalajara",
    "Helsinki",
    "Hiroshima",
    "Oslo",
    "Nueva Orleans",
    "Búfalo",
    "Bucarest",
    "Richmond",
    "Liverpool",
    "Memphis",
    "Jacksonville",
    "Luxemburgo",
    "Porto Alegre",
    "Hannover",
    "Campinas",
    "Ciudad del Cabo",
    "Honolulu",
    "Ottawa",
    "Venecia",
    "New Haven",
    "Valencia",
    "Florencia",
    "Caracas",
    "Nottingham",
    "Toulouse",
    "Newcastle",
    "Ginebra",
    "Sofia",
    "Medellín",
    "Porto",
    "Madison",
    "Little Rock",
    "Albuquerque",
    "Sheffield",
    "Salvador",
    "Hsinchu",
    "Knoxville",
    "George Town",
    "Casablanca",
    "Dayton",
    "Allentown",
    "Strasbourg",
    "Columbia",
    "Bolonia",
    "Cardiff",
    "Sevilla",
    "Vitória",
    "Greenville",
    "Fortaleza",
    "Kagoshima",
    "Quebec",
    "Cracovia",
    "Akron",
    "Springfield",
    "El Paso",
    "Edimburgo",
    "Winnipeg",
    "Alejandría"
)

public var listOfStuffs: List<String> = listOf(
    "tijera",
    "peine",
    "cepillo",
    "escoba",
    "silla",
    "mesa",
    "coche",
    "sirena",
    "cesto",
    "sillón",
    "televisor",
    "radio",
    "robot",
    "celular",
    "soldado",
    "casa",
    "caja"
)